[platformio]
default_envs = slave

[env:slave]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv

lib_deps =
    bblanchon/ArduinoJson@^7.4.2

lib_extra_dirs =
    ../common/lib

build_flags =
    -I../common/include
    -D CORE_DEBUG_LEVEL=5
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -D NODE_ID=\"node_2\"
