[platformio]
default_envs = pico2w_check

[env:pico2w_check]
# Using the Earlephilhower platform for RP2350 support
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2w
framework = arduino

upload_protocol = picotool

monitor_speed = 115200
